# Generated by Django 5.2.13 on 2026-05-15 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manim_math_pad', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animation',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('generating', 'Generating Manim scene'), ('rendering', 'Rendering video'), ('completed', 'Completed'), ('failed', 'Failed'), ('canceled', 'Canceled')], default='pending', max_length=12),
        ),
    ]
